server:
  port: 9025

spring:
  profiles:
    active: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    driver-class-name: org.h2.Driver
    initialization-mode: always
    username: sa
    password:
  h2:
    conole:
      enabled: true
  jackson:
    time-zone: Asia/Baku
    default-property-inclusion: always



